name: CI (Julia nightly)
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'
  workflow_dispatch:
jobs:
  test-julia-nightly:
    name: ${{ matrix.version }}/${{ matrix.os }}${{ matrix.arch }}/t=${{ matrix.threads }}/${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
        version:
          - 'nightly'
        os:
          - ubuntu-latest
        threads:
          - '1'
          - '2'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          coverage: false
        env:
          JULIA_NUM_THREADS: ${{ matrix.threads }}
