name: CI 
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'
  workflow_dispatch:
jobs:
  test:
    name: ${{ matrix.version }}/${{ matrix.os }}${{ matrix.arch }}/t=${{ matrix.threads }}/${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
        version:
          - '1'
        os:
          - ubuntu-latest
        threads:
          - '1'
          - '2'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      # TODO: remove the following line once StrideArrays is registered
      - run: julia --color=yes --project -e 'import Pkg; Pkg.develop(Pkg.PackageSpec(url = "https://github.com/chriselrod/StrideArrays.jl"))'
        shell: bash
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          coverage: false
        env:
          JULIA_NUM_THREADS: ${{ matrix.threads }}
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      # TODO: fix the following lines once StrideArrays is registered
      - run: |
          julia --project=docs -e '
            using Pkg
            pkgs = [PackageSpec(path = pwd()), PackageSpec(url = "https://github.com/chriselrod/StrideArrays.jl")]
            Pkg.develop(pkgs)
            Pkg.instantiate()'
        shell: bash
      - run: |
          julia --project=docs -e '
            using Documenter: doctest
            using BLASBenchmarks
            doctest(BLASBenchmarks)'
        env:
          JULIA_NUM_THREADS: 2
      - run: julia --project=docs docs/make.jl
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JULIA_NUM_THREADS: 2
